### ISSUE TITLE
Plugin channels being ignored

### ISSUE THREAD

**Issue by CullanP** [ViaVersion/ViaVersion#1318]
**Is your feature request related to a problem? Please describe.**
Our anti-cheat looks at specific plugin channels when it decides to ban and I only recently noticed viaversion is skipping some crucial channels we need causing a lot of people who are using hacked clients to login, The line at fault would be here https://github.com/ViaVersion/ViaVersion/blob/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/packets/InventoryPackets.java#L174

**Describe the solution you'd like**
I'd like to see an event or some sort of API so I can hook into this and run code when a plugin channel is ignored, I'm fine with any alternative so long as I can view/read these channels being ignored

**Comment by MylesIsCool** [comment]
The reason channels are ignored boils down to a few things:
- If the channel doesn't meet 1.13 channel format, we're unsure of how to rewrite it so we don't
- If your behind Bungee and we rewrote channels, Bungee may not filter channels correctly.

1.14 uses a different channel format so your plugin messages aren't going to work anyway in general. 
On incoming if properly formatted the 1.14 plugin channels are still accessible in Bukkit / ProtocolLib. On outgoing they need to be changed to the 1.14 format (which may be just a simple if statement).

Otherwise it's not something that we'll make an API for (mainly because it's not needed by our wider audience) and I'd suggest forking ViaVersion otherwise.

**Comment by CullanP** [comment]
Well I was already aware it was changed due to a versioning reason, I was simply asking for a way around this seeing as it pretty much eliminates something many owners/devs use to read plugin channels, This also eliminates the possibility of blocking out certain mods. I wanted to avoid forking viaversion if possible as applying a patch simply because this plugin is ignoring plugin channels is extremely annoying, however I guess I don't have a choice.

**Comment by MylesIsCool** [comment]
I'm not really sure what you could be reading on the incoming channel in regards to blocking out certain mods, if a 1.13 client is sending 1.13 data it's going to get passed through. If a 1.13 client isn't it won't (neither will it on a 1.13 server).

If you can provide examples of issues with this, we can look into further options but at the moment I'm not seeing the main issue.

**Comment by CullanP** [comment]
This is the problem, even if I used protocollib to try to intercept the packets viaversion is still changing the packet so my plugin doesn't detect what it needs to, here's an example: http://puu.sh/DoEbl/6ef63d2613.png, This was me using protocollib after you said you can use protocollib to read the packets, when in-fact you can't as viaversion is modifying the packet before protocollib gets it, even if I were to try to read it directly from the server it wouldn't work as it's all ran through the netty handler first, I had a similar issue with grabbing client versions on join, however got a workaround using reflection

**Comment by CullanP** [comment]
It's fine, I appreciate the help, I'll figure this out.

**Comment by MylesIsCool** [comment]
I don't think I'm quite on the same page because you're sending "LOLIMAHCKER" which even if ViaVersion didn't cancel the sending the client wouldn't understand because it's not 1.13 format? "namespace:name"

If you're looking to send for lower clients and just want to not see the debug, disabling 1.13 conversion errors in config is the way to go.

**Comment by CullanP** [comment]
I'm not sending that, the client is sending it to us. Our anti-cheat currently uses incoming plugin channels to detect that channel and viaversion is preventing that from happening. I send a specific string to the client and it gives us a response via a payload packet, however viaversion is stopping it. If I don't send that string, it won't come up via viaversion at all as there's nothing to look for anymore.

**Comment by MylesIsCool** [comment]
So what version is the hacked client on?

**Comment by CullanP** [comment]
It's on 1.13, I figured out a workaround now though and solved the problem. I appreciate you going out of your way to try to figure out this problem we're having.

**Comment by FeaturedSpace** [comment]
@MylesIsCool I'm still getting the error even after following the format:

```
[ViaVersion] Ignoring plugin channel in incoming REGISTER: NetworkCore:Main
```

**Comment by MylesIsCool** [comment]
> @MylesIsCool I'm still getting the error even after following the format:
> 
> ```
> [ViaVersion] Ignoring plugin channel in incoming REGISTER: NetworkCore:Main
> ```

The format is lowercase

**Comment by FeaturedSpace** [comment]
@MylesIsCool thank you!
