### ISSUE TITLE
bug lwc and chairs from viaversion on 1.12.2 and lower ver with 1.13+

### ISSUE THREAD

**Issue by gyamyro** [ViaVersion/ViaVersion#1361]
**Describe the bug, provide any errors**
Its a bug from visual shield an nonshield server ...
when someone  click on chair plugin stairs or ride a horse and spam simultan on a chest with visual nonexist shield that person can open other person chest

**How can we reproduce it?**
1. Login on 1.12.2 server with 1.13+ client ver (viaversion)'
2. Click on stairschairs plugin or click to ride a horse
3. use a visual shield bug 
4 do that very fast and click on locked chest
5 you can open that locked chest (lwc)

**Expected behaviour**

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by MylesIsCool** [comment]
If your server is 1.12.2 and the issue happens on that version it's not down to ViaVersion as we don't touch info for the server version.
Otherwise if your issue is with a version lower than 1.12.2 it concerns ViaBackwards or ViaRewind.

Otherwise if I've misunderstood, you'll need to fill in all the sections of the issue and provide a video and look over what you've written as some of it is hard to understand.
