### ISSUE TITLE
Players getting kicked when doing a JSON based command

### ISSUE THREAD

**Issue by Zaino60** [ViaVersion/ViaVersion#1369]
**Describe the bug, provide any errors**
There seems to be an incompatibility between ViaVersion and FurnitureLib. My Creative server is 1.12 (using latest via) and it seems that on any 1.13.X and 1.14.X clients when you do the /furniture list command you get kicked.
I sent the kick message to the FurnitureLib dev and he said it's a ViaVersion issue: https://www.spigotmc.org/threads/furniturelibary-protectionlib.77537/page-89#post-3391724

I enabled debug on server.properties and here's the full error of the kick: https://pastebin.com/epZrwHae

**How can we reproduce it?**
1. Login on Minecraft 1.13+ on a Spigot 1.12 Server w/ ViaVersion (latest), DiceFurniture (latest) and FurnitureLib (latest)
2. Do the command /furniture list
3. Get kicked

**Screenshots**
https://gyazo.com/1f4ab3be75afe3e7b0054018c59f88b8.

**ViaVersion Dump:**
https://dump.viaversion.com/56046f25e0e3c0f745b379e94ed8b6e041839cfe9a12309f83926ab340f5a06e

**Additional server info**
- Kick message: https://pastebin.com/epZrwHae
- This server is running Paper version git-Paper-1611 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- Part of a BungeeCord Network but ViaVersion is spigot side, not bungee

**Comment by KennyTV** [comment]
`com.kirelcodes.miniaturepets.packetListeners.PacketHandler.write(PacketHandler.java:37)` might be the problem

**Comment by MylesIsCool** [comment]
This is the JSON chat library that we use error'ing which the error means that the JSON click event is badly formatted - https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/chat/BaseComponentSerializer.java#L60

I would highly suspect the plugin has invalid JSON, mainly because click events work fine otherwise.

My hint for the author would be nextCommand and prevCommand may be null in their page system.
