### ISSUE TITLE
Force allowing BlockPlaceEvent causes placing on own location to be ignored

### ISSUE THREAD

**Issue by MrEAlderson** [ViaVersion/ViaVersion#1382]
**Describe the bug, provide any errors**
Block is getting placed even if it shouldn't. Works just fine when joining with the native server version

**How can we reproduce it?**
1. Install paper 1.8.8
2. Create a test plugin which is listening to the 'BlockPlaceEvent' and invoke 'event.setCancelled(false)'
3. Place a block directly under the player while the player isn't flying but standing on an other block
4. Has been tested with 1.14.3, but will probably also occur with any non 1.8 version

**Expected behaviour**
Block shouldn't be placed at that situation, works just fine on latest normal spigot 1.8.8

**Screenshots**
https://streamable.com/s/0sl2d/ikslnx

**ViaVersion Dump:**
https://dump.viaversion.com/743a8845c3e57057f1d1af3443dd257ca3be6a1a1874e19ed1955a5452733816

**Comment by MylesIsCool** [comment]
This is because of the paper patch - https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/us/myles/ViaVersion/bukkit/listeners/protocol1_9to1_8/PaperPatch.java

The best patch we could do is changing the event level, I'm not sure why you would want to uncancel an event though. 

Would event priority HIGHEST work better?
