### ISSUE TITLE
Can not register my own protocol

### ISSUE THREAD

**Issue by H4kt** [ViaVersion/ViaVersion#1489]
**Describe the bug, provide any errors**
I wanted to override some packets in Protocol1_14To1_13_2
So I created a class, which extends it
Then I registered it using `ProtocolRegistry::registerProtocol()`

By the way when I join  the server with MC 1.14.4 this happens:
https://hastebin.com/epijonecon.md

I think I'm doing something wrong. If so please tell me the right way to make it.

**ViaVersion Dump:**
https://dump.viaversion.com/8efae163dd8301da7f777a2b1b21ad5f37a5c7b5119c3cb110bb6d1116e8e24d

**Additional server info**
 Running Paper version git-Paper-1618

**Comment by MylesIsCool** [comment]
Could you provide the code?

**Comment by H4kt** [comment]
Yeah, sure.
Registration in my main class:
`ProtocolRegistry.registerProtocol(new InjectionProtocol(), Arrays.asList(477), 404);`

And the InjectionProtocol.java:
`package ru.h4kt.*hidden*;

import us.myles.ViaVersion.protocols.protocol1_14to1_13_2.Protocol1_14To1_13_2;

public class InjectionProtocol extends Protocol1_14To1_13_2 {

}`

**Comment by MylesIsCool** [comment]
So one of the ViaVersion people (creeper) realised that by extending the original class certain methods will break because they reference the protocol class. 

Is there anything specific you want to override? We'll look into providing methods to make this nicer and not cause issues.

**Comment by H4kt** [comment]
Basically I need to override a few packet re-mappers to update the contents of that packets for some 'special' players. Like update a block in a ChunkData packet and e.t.c.

**Comment by H4kt** [comment]
Btw forgot to mention that in can be both incoming and outcoming packets

**Comment by H4kt** [comment]
Could you please tell me when, approximately, you will make this happen? xD

**Comment by MylesIsCool** [comment]
It might take some time because we'd like to clean up some of the internals. As much as this solution isn't the cleanest, https://github.com/MrMicky-FR/ViaChatFixer/blob/647bcc8722295171aee004064dfa857b427c92ec/common/src/main/java/fr/mrmicky/viachatfixer/handlers/via/ViaChatHandler.java is a pretty good example of replacing the handlers.

**Comment by H4kt** [comment]
It worth a try, but how does that supposed to register?

**Comment by MylesIsCool** [comment]
> It worth a try, but how does that suppose to register?

You need to modify the existing protocol, extending a protocol currently doesn't work. You could copy all the code in theory and also do it that way (modifying any .send() methods to use the right protocol)

**Comment by H4kt** [comment]
I tried coping everything and it didn't make a trick. The same exceptions were printed. Could you just let me know know when you will finish. I'd prefer to wait for the cleanest solution.

**Comment by MylesIsCool** [comment]
@H4kt When you tried the above approach, did you duplicate things like the the classes in https://github.com/ViaVersion/ViaVersion/tree/master/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets ?

I'm happy to add an API, are you planning to use this for a public plugin or private solution? If it's a public plugin it would be worth noting that it could be the next major update before something like this would work for most servers.

The reflection approach is a pretty good solution (if you need it publcily before lots of servers update)  - https://github.com/MrMicky-FR/ViaChatFixer/blob/647bcc8722295171aee004064dfa857b427c92ec/common/src/main/java/fr/mrmicky/viachatfixer/handlers/via/ViaChatHandler.java

Otherwise, if you're able to give a preview of which classes you've copied I should be able to help further.

**Comment by H4kt** [comment]
Since it is a private plugin for now (it may become public after some time) I'd like to try this solution to finish our server update on time.
I'll try the reflection solution today and give you some feedback whether it's working or not.

**Comment by H4kt** [comment]
And now I found out that I actually do not understand how to modify packets.
I'm just getting kicked for IndexOutOfBoundsException.
Nothing appears in the console, only message on client.

Another strange thing is that I can't `.get()` the POSITION value it says that it's not there.

Here is my code
```
Player player = ViaUtils.getPlayer(wrapper.user());
World world = player.getWorld();

Position position = wrapper.read(Type.POSITION1_14);
Location location = new Location(world, position.getX(), position.getY(), position.getZ());

WrappedChunk chunk = WrappedChunk.find(location.getChunk());
if (chunk == null) {
	return;
}

VisualBlock block = chunk.getBlock(location);
if (block == null) {
	return;
}

SupportedBlock type = block.getType();
if (type == null) {
	return;
}

Version version = Version.getPlayerVersion(player);
if (version.isHigherOrEqual(type.getVersion())) {
	return;
}

wrapper.write(Type.VAR_INT, type.getID());
```

![image](https://user-images.githubusercontent.com/50774419/67625746-af126f00-f84a-11e9-8d43-a7d6d747f2a7.png)

**Comment by MylesIsCool** [comment]
If you read a position, you'll need to remember to write the position (see .passthrough if you want to pass it through)

**Comment by H4kt** [comment]
Ok, that did the trick.
Thanks a lot again.

**Comment by FormallyMyles** [comment]
In 3.0.0 you will be able to fetch the protocol from the registry and then can override packets, so closing this :)
