### ISSUE TITLE
Send message when given incompatible block

### ISSUE THREAD

**Issue by AwesomestCode** [ViaVersion/ViaVersion#1544]
**Problem:**
Players get confused when a block they try to place (in the creative server) suddenly disappears.

**Solution**
Send a message when the block is removed due to it being incompatible with the server version.

**Comment by Xernium** [comment]
Not happening. The creative inventory is nearly impossible to control with version mismatches. That is mainly because many actions a creative inventory can perform don't need to be or won't be transmitted or registered to a point that's possible at.

**Comment by MylesIsCool** [comment]
See above :)

**Comment by AwesomestCode** [comment]
How does Hypixel do it on their build battle server though? It must be possible, given that it has been done. Can’t you just check for an invalid block ID?

**Comment by Xernium** [comment]
@AwesomestCode As I said; It might not be impossible to implement. That said that is another project on its own entirely. Hypixel uses a very intensively modified Minecraft server that maybe more easily be able to detect this. But with the current implementation ViaVersion would need a unique set of transformers from each to every other version of the creative inventory (because it’s inconsistent) and that’s certainly not the goal of the project

**Comment by Xernium** [comment]
What might also work to their advantage is that their servers all operate on the same base game version. They know beforehand what exists and what not. ViaVersion can’t work like that.

**Comment by AwesomestCode** [comment]
Not asking to transform the blocks within the creative inventory. When they are placed, send a message in the same part where viaversion intercepts the block placement. Since viaversion is already handling the removal of the block, I don’t see what would be so hard about adding a send message instruction within the same method.

**Comment by Xernium** [comment]
You don’t understand. The block is never removed. It’s remapped. The server never removes it. The *invalid* data is just lost during the translation. It would not be a worthwhile idea to create an event whenever that happens because then you might as well call an event for each packet.

**Comment by AwesomestCode** [comment]
Listen to an exception from the server about invalid packets, and send a general message about not being able to perform the action?

**Comment by Xernium** [comment]
That’s not how this works. That’s not how any of this works. ViaVersion is a translator so that you do **not** get incompatibilities. You want an event fired whenever something is remapped (to stone) so you can send a message. Maybe or maybe not something to consider. Would be highly conditional after all of it.

**Comment by AwesomestCode** [comment]
Ummm, sorry if I was ambiguous but that’s not what I wanted. Not for every remap. Here is the sequence, please tell me at which step I went wrong.
Original sequence:
ViaVersion starts on 1.8 server.
Client logs in in creative mode using a 1.12 client. Login is translated by viaversion.
Client places a new block, say, glazed terracotta
ViaVersion translates the place block, but since the block doesn’t exist it fails to translate the block. Nothing happens, no block placed.
Client receives information back from the server saying that there was no block there. Everything is now the same as it started.

I want it to be so that ViaVersion realizes it could not translate it and add a chat message. Please correct me if I messed up my sequence of events.

**Comment by Xernium** [comment]
That already starts with placing the block in the inventory. In a perfect world it should vanish or turn to minecraft:stone but it sometimes doesn’t. If it doesn’t and you place it down- The packet you send will either make the server think you spawned something in and retroactively update your inventory which will have one of the aforementioned outcomes or it will actually try to place the block in which case ViaVersion translates the packet and since ViaVersion doesn’t care about creative the packet that gets picked up gets invalidated. So depending on how it’s picked up it doesn’t even get far enough for the server to recognize that this is an invalid creatively spawned item. Which relates back to what I said in my first message. The creative inventory is hard to control. It creates lots of unwanted behavior as a result. I’ve seen networks get around this by force updating a players inventory to check for those *invalid* items every so often. Again also not a solution.
