### ISSUE TITLE
Broken Boss Bar API in 2.2.0+

### ISSUE THREAD

**Issue by 4ch3los** [ViaVersion/ViaVersion#1572]
**Describe the bug, provide any errors**
Since the release of 2.2.0+ the BossBar Api seems to be broken and just throws an exception when trying to use it
https://haste.4ch3los.de/jimarawaxi.css

**How can we reproduce it?**
1. Try to use the bossbar api

**ViaVersion Dump:**
https://dump.viaversion.com/58ee0dc356df32cc116b8a7ae8c4f4e3f8a454700c90cbf88efdf3c33ba283c6

**Comment by Gerrygames** [comment]
The boss bar API is only designed to work on 1.8.9 servers and 1.9+ clients. It most likely worked before because the boss bar packet didn't change until 1.15. The exception is an intentional trap to prevent sending packets with a protocol that is not in the current pipeline. There have been several very hard to find issues in ViaBackwards where a ViaVersion protocol was accidentally used when sending packets.
We don't plan on extending the boss bar API to support all versions. Especially since when you're on Spigot 1.9+ you can just use the Bukkit boss bar API instead.
