### ISSUE TITLE
Water swimming advantage [IMPORTANT]

### ISSUE THREAD

**Issue by SrLeojaco** [ViaVersion/ViaVersion#1671]
Since a newer Minecraft version (1.13) a fast swimming feature when diving was introduced: https://minecraft.gamepedia.com/Swimming

This causes that 1.13-1.15 players have advantage over 1.8 and 1.12 on 1.8 servers since they can go really quick underwater (some anticheats may teleport they back, but that's a really dirty prevention).

> "Sprint-swimming, like normal sprinting, ends when the player collides with a solid block, sneaks, blocks or attacks a mob. Additionally, sprint-swimming also ends if the hunger bar decreases to 6 () or below." (Minecraft WIKI)

1 month ago i reported a similar advantage with vines (https://github.com/ViaVersion/ViaVersion/issues/1640) that was resolved by hidding the vine if they were not connected to any block. This is not possible here since taking out the water would be also an advantage and horrible experiencience.

I don't have any ideas for this, but for now i'm blocking that versions on the most advantage servers

**Comment by KennyTV** [comment]
A proper fix for this isn't possible (especially on a packet level due to ordering and necessary caching), since the server has limited power in controlling client poses.

A possible workaround would be to make plugin set the hunger of the player below its sprinting limit, then reset it when the player leaves the water (... this however might not work in the future, since the limit might be removed with the anncounced combat changes).
