### ISSUE TITLE
Error (and maybe have crashed my server)

### ISSUE THREAD

**Issue by AymerickA** [ViaVersion/ViaVersion#1771]
**Describe the bug, provide any errors**
https://framabin.org/p/?d97fe06a60bb6c4a#V6Lyh4oxhJTWSa1QAWKWiH91+Zbzp1etk4GwaMW9ZoY=
and
https://framabin.org/p/?d8d3389572440cf5#TIQ8mNu3YTouTXHSJrmYNLsHaYruafayLfPmW5wLugs=

**How can we reproduce it?**
Don't know sorry

**ViaVersion Dump:**
https://dump.viaversion.com/3bd6f6279d9aad7943bac175ebeb05248e043d0fb28071e5b762c4b46c64fdea

**Additional server info**
I use a proxy (Travertine fork of Waterfall for 1.7-1.15) and my list of plugins is in viaversion dump

**Comment by FormallyMyles** [comment]
The initial skull error is due to something not sending skulls right and won't crash your server.

The error afterwards is some lockup on your server, ViaVersion is purely packet translation (for the most part) so it can't crash your server this way, and is probably a bug in a plugin using GUIs or an exploit.
