### ISSUE TITLE
us.myles.ViaVersion.exception.InformativeException:

### ISSUE THREAD

**Issue by GabRayz** [ViaVersion/ViaVersion#1854]
A Viaversion error showed up in our logs. We have no idea where it comes from.
Here's the logs: 
[error.log](https://github.com/ViaVersion/ViaVersion/files/4842261/error.log)
[viaversion dump](https://dump.viaversion.com/bdbb44b85e8ead529cc75cd17ba4b2569d7fd8003df6148e6ff6b97be8f769a7)

Were are using bungeeCord, our server is currently in 1.15.2.
I don't really have more details to give, hope the logs are enough :/
I'm open to questions if it can help.

**Comment by Noiknez** [comment]
**Describe the bug, provide any errors**
The error happened on the console
Full log : https://pastebin.com/wgrajEhU

**How can we reproduce it?**
I don't know how to reproduce it

**Expected behaviour**
No error on the console

**ViaVersion Dump:**
https://dump.viaversion.com/bdbb44b85e8ead529cc75cd17ba4b2569d7fd8003df6148e6ff6b97be8f769a7

**Additional server info**
Server version : This server is running Paper version git-Paper-372 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
The server use Bungeecord but viaversion & viabackward but it is just installed on the server, not bungee
Server plugins : Plugins (25): BungeeTabListPlus, Cartographer2, Citizens, CraftingStore, DiscordSRV, FastAsyncWorldEdit, HeadDatabase*, HolographicDisplays, Images*, IPWhitelist*, LuckPerms, Multiverse-Core, Plan, Prism, ProtocolLib, spark, Tesseract, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard
Bungeecord version : This server is running BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.2-SNAPSHOT:26f538d:1515 by md_5

**Comment by ElBananaa** [comment]
Hey! Same issue

Entire latest.log:
https://pastebin.com/SaG4Z4Zq
I don't know, it just happened randomly.

ViaVersion Dump:
https://dump.viaversion.com/5408943ed2760c9e6b9624f2d2c6ef858d53a245e774b937095b529e4677d2fa

Additional server info:
Server version : git-Paper-1618 (MC: 1.12.2)

Server plugins: (All up-to-date)
![image](https://user-images.githubusercontent.com/53318613/85952487-fcab2280-b969-11ea-9603-ec5ab124908d.png)

**Comment by KennyTV** [comment]
These are simply invalid initial connections, but before, we never had any logging for them. They will now only be printed with Via debug enabled
