### ISSUE TITLE
1.16.1 SkinsRestorer & ViaVersion incompatibility 

### ISSUE THREAD

**Issue by xknat** [ViaVersion/ViaVersion#1873]
our refresher: [[link](https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/bukkit/skinfactory/LegacySkinRefresher_v1_16_R1.java)] 
Refresher when they use paper: [[link](https://github.com/SkinsRestorer/SkinsRestorerX/blob/f53f5a8768521abe71f45c8e9d3bb5bf72b4da3c/src/main/java/skinsrestorer/bukkit/skinfactory/PaperSkinRefresher.java)]
Local git ticket: https://github.com/SkinsRestorer/SkinsRestorerX/issues/277

**Is your feature request related to a problem? Please describe.**
Incompatibility between the new world manager and previous versions are not working when using both ViaVersion & SkinsRestorer. 

**Describe the solution you'd like**
Our dev pointed out that This issue might be on viaversion side.
Therefor we created this issue and await your feedback.

**Describe alternatives you've considered**
N.A.

**Which versions is this for?**
when using 1.16.1 and allow connections from 1.15.2 till 1.8.8
Versions are any (releases) that support 1.16

**Comment by FormallyMyles** [comment]
I'm confused about what you're asking, what versions does this happen on?

"when using 1.16.1 and allow connections from 1.15.2 till 1.8.8
Versions are any (releases) that support 1.16"

Server version? Client version?

If it only happens on 1.16 server this should be opened on ViaBackwards. Otherwise, if it's an incompatibility with the new world manager, do you know what part is incompatible?

**Comment by xknat** [comment]
AaaH, should be on via backwards 🤦  
all these project names.

alright cheers will move it over to there.

**Comment by KennyTV** [comment]
Please include the information myles asked for. 👀
