### ISSUE TITLE
Test vote kicked me off server

### ISSUE THREAD

**Issue by Ac3dUd3** [ViaVersion/ViaVersion#1875]
The error log sent me here, I tried to run a test vote as i am setting up voting and I got kicked.

I am using latest versions of NuVotifier and VotingPlugin and on paper-44 the current latest build

https://pastebin.com/hj859sWp

**Comment by Jo0001** [comment]
We need more information about your setup:
**How can we reproduce it?**
Steps to reproduce the behavior:
1. Login on **'
2. ...

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**ViaVersion Dump:**
- Type `/viaversion dump`, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by KennyTV** [comment]
Based on the little you gave us, I'll just say update ViaBackwards to its dev build on https://ci.viaversion.com/
