### ISSUE TITLE
ViaVersion is modifying client information

### ISSUE THREAD

**Issue by ShayBox** [ViaVersion/ViaVersion#1914]
ViaVersion is modifying the clients protocol version during server list ping, this is done so the underlying server doesn't return unsupported version on the server list, this has the downside of breaking plugins that need clients protocol version, an alternate method used by similar plugins like ProtocolSupport is to change the underlying response from the server by either modifying the logic used to craft the response or packet manipulation similar to what's used now.

I would also like to add, even using protocollib with highest priority doesn't get around this manipulation, there is no way to get the clients correct protocol version without modifying ViaVersion.

**Comment by FormallyMyles** [comment]
"there is no way to get the clients correct protocol version without modifying ViaVersion.", The ViaVersion API is for this.

**Comment by ShayBox** [comment]
So you want every plugin that's accessing vanilla data with normal events to add viaversion's api to their project just so they don't break? it seems like changing where the modification happens from the clients data to the servers response seems to make more sense.

**Comment by KennyTV** [comment]
Anything we will apply to packets will - by design - not be visible for any other protocol injector, which is why you have to use Via API if you run it on your server. PS fully recreates ping responses and injects the data into the server itself to make things work.

**Comment by ShayBox** [comment]
What do you know, the api even returns the wrong version too, the only way I can get the correct version is using protocolsupport so viaversion has to disable parts and use their api which returns the correct protocol version.

**Comment by Xernium** [comment]
The Via* API will only return the correct version for a connection if the connection is made through the running Via* plugin. So for example if you have ViaVersion ViaRewind and ViaBackwards on a server, no proxy (velocity or bungeecord or similar) or no proxy with Via plugins installed on it, and you don’t **have ProtocolSupport installed** then it will always return the correct version.    
Gotchas: While ProtocolSupport is installed ViaRewind and ViaBackwards will cease function even if installed because ProtocolSupport replaces their functionality.     
While ProtocolSupport is installed Via will inject after ProtocolSupport so it physically can’t know a client version older than the server version because that’s already translated by ProtocolSupport.    
Likewise if Via* does the translation of the protocol while it’s run on a proxy, the server will only see the already translated protocol, thus showing incorrect results.
