### ISSUE TITLE
tab list does not update

### ISSUE THREAD

**Issue by Almog292929** [ViaVersion/ViaVersion#1967]
**Describe the bug, provide any errors**
when using via version on a 1.15.2 server and logging from 1.16.x with bungee when you go between servers the players in the tablist does not update.

**How can we reproduce it?**
1. Login on 1.16.1
2. login to a bungeecord server with 1.15.2
3. move between the servers and watch the tab
the players from one server will stay on the tab list.

**Expected behaviour**
when the player move to a new server the tab should update.

**Screenshots**
[screenshot](https://imgur.com/a/5MqSysU)

**ViaVersion Dump**
https://dump.viaversion.com/9710ebe764c760bb60c7da8edb0e23bfbfce155d72621dd619f8ab1608e7528c

**Additional server info**
i use bungeecord

**Checklist**
- [ * ] I have included a Viaversion dump
- [ - ] If applicable, I have included a paste (not a screenshot) of the error
- [ * ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
What player is switching servers and who can still see the old player?

**Comment by Almog292929** [comment]
the player using the 1.16.1 client is switching, named tknudjnu in the image, and he is the one that still see the old player, this problem does not appear when im using 1.15.2.

**Comment by KennyTV** [comment]
Try and remove plugins until the issue doesn't occur anymore, this is likely plugin related

**Comment by Almog292929** [comment]
it got fixed after removing viaversion

**Comment by BuzzTheGamer23** [comment]
Well, of course, because then you cannot join the versions that have the issue. Make ViaVersion the last plugin you remove (and, if you have ViaBackwards and/or ViaBackwards, remove the Via plugins all at once or ViaRewind/ViaBackwards before ViaVersion) when people on the ViaVersion Github/Discord tell you to remove plugins until it fixes it.

**Comment by Almog292929** [comment]
I cannot remove all the plugins as it will destroy most of my already configured server, i added via version today and the problem appeared after installing, as this bug only happens when using 1.16.1 and not 1.15.2 its a problem with via version.
I have 3 servers runing 1.15.2 with via version and one 1.16.1 without.
When removing via version and going between the 1.15.2 server the problem does not accure, even with via version if my client is on 1.15.2 the tablist works perfectly, it only happens when im using the 1.16.1 and moving betwewn servers

**Comment by BuzzTheGamer23** [comment]
Either make a copy of the server and test it using that copy or backing up the plugins folder then doing it.

**Comment by Almog292929** [comment]
I am not able to do that as my server to big for downloading and would take alot of time to reconfiger everything

**Comment by BuzzTheGamer23** [comment]
Then do the other one I said; backing up the plugin folder, then doing the test, then restoring the plugin folder backup afterward. Make sure to read the whole message. And, if you don’t want to remove all of them individually, remove half of the plugins, then if it fixes it, the plugin with the issue is in the half you removed, but if it didn’t, it is in the half you kept, so, repeat it with the half with the issue. Do this until you find the plugin (make sure to remove the Via plugins last). And, by remove, I mean either moving the plugin to another folder, or changing the .jar in the plugin name to something else, then when adding it back if the issue is ever in the half you removed, changing it back to .jar or moving back the plugin.

**Comment by Almog292929** [comment]
I read the messege and yet im not able to do that, removing any plugins from my server will couse many other plugins to cruah and currupt and i dont want to start reconfigering everything from scartch.
Telling me over and over to remove other plugings wont resolve the issue as it only started happening when I installed Via version, it all worked flawlessly until then, i also just tried to delete every plugin from my test server and installing via version only. The problem still happent but the server i log to it from did still had all the plugins it originaly had, 
Anyway, other than that the plugin works flawlessly, its just a shame that there is no way to resulve this issue

**Comment by BuzzTheGamer23** [comment]
That is why I said to back up the plugins folder before then restore it after. I told you to read the whole message before you send a response.

**Comment by Almog292929** [comment]
Sorry but im not able to do that for all the servers for personal resons, im just letting you know that this problem exist and that it should be fixed, im not able to start deleting files and plungins from my server when im certien that the problem is with this plugin

**Comment by BuzzTheGamer23** [comment]
I see you use TabList. ViaVersion and TabList don’t work together very well. I would suggest swapping to a different plugin.

**Comment by Almog292929** [comment]
Okay i will try

**Comment by KennyTV** [comment]
As said, this is likely plugin related. If you do end up reproducing it on a clean setup, we will reopen this.
