### ISSUE TITLE
Mounting issue

### ISSUE THREAD

**Issue by FzzyTV** [ViaVersion/ViaVersion#2119]
When using a 1.16 client, players on my server cannot mount anything, (Boat, horse, pets) it works fine when using 1.8.8 - 1.15 client.

**How can we reproduce it?**
Steps to reproduce the behaviour:
1. Login on 1.16 client'
2. Connect to fzzymc.net, go to factions 
3. Try to get into a boat
4. a moderator in your discord by the name of Jo0001 🇩🇪 was able to replicate this error on their own test server

**Expected behaviour**
The user will glitch around and not be able to move in the boat 70-80% of the time

**Screenshots**
https://www.youtube.com/watch?v=E7FoBOqv_dE&feature=youtu.be&ab_channel=Fzzy
This is a video of what happens when trying to get into a boat.

**ViaVersion Dump**
https://dump.viaversion.com/c724972c2c836bc1fd0d9aef334b652a019366867937db273e1f30613b35c0c4

**Additional server info**
i use bungeecord (Auto Updating to the newest version)

**Checklist**
- [yes] I have included a Viaversion dump
- [yes] If applicable, I have included a paste (not a screenshot) of the error
- [yes] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Jo0001** [comment]
Also happens in Survival Mode: https://cdn.discordapp.com/attachments/676144522308354103/762694917813960725/Minecraft_1.16.3_-_Multiplayer.mp4

**Comment by ninomato** [comment]
Any update on that issue? We're waiting for a fix - very important system for our server.

**Comment by draand28** [comment]
Still no fixes? No pull requests, forks, workarounds? We are nearing the release of 1.17 and still there is no fix for 1.16.

**Comment by Xernium** [comment]
Hey there! Unfortunately the "Legacy" label means that this is a low prority issue.
Taken from the ViaVersion Discord:

## About ViaVersion on Legacy (pre 1.13) servers

There is a message that displays on legacy servers warning you about the age of your server software and state of the plugin in this regard.
It boils down to this:

### You will still be able to run Via on legacy servers in the future.
We won’t remove the ability to run Via on legacy servers, as that would just spawn another plugin or project.

We, ourselves, won’t fix bugs that are exclusive to legacy servers anymore. 
### Community provided bugfixes are still welcome

What this means essentially is that *we won’t put any more effort into maintaining legacy versions.* 
It’s taking more and more time to do so and at the end of the day, you must understand that we are getting tired of it. 
This is especially true since newer game logic makes this more and more impractical, and that is even more true if you consider Via is being run and translates at the network level.

We’ve thought long and hard about this and the decision is final. However this message may change to more clearly convey our intentions

## What that means for this issue
We acknowledge its existence. Someone may fix it in the future.
But please know, 1.9 completely overhauled the entity mounting and movement mechanics and our current workaround was bound to not work forever.
That said, this issue will remain here.

**Comment by RaphiMC** [comment]
I also looked into this issue and can confirm that it happend to me with only VV on a 1.8 spigot server and only with 1.16+ client.
Can confirm, only happens sometimes (sometimes the boat just works)

Heres a comparison between the packets (1.16 (left)/1.15.2 (right)). The red marked entry is most likely the packet that breaks boats as it dismounts the player clientside from the boat after one tick of being in the boat
![grafik](https://user-images.githubusercontent.com/50594595/109617486-bcbebf80-7b36-11eb-8b16-39b1298635b3.png)

**Comment by draand28** [comment]
I have tested latest viaversion dev 3.3.0-21w08b with 21w08b snapshot client and the mounting issue in 1.8.8 servers is not present anymore. Maybe this will provide some insight into how to fix it.

**Comment by KennyTV** [comment]
Preeetty sure that's a bug Vanilla fixed in the 1.17 snapshots with dismount handling on the client, so unsure if we even want to do anything about that.

**Comment by KennyTV** [comment]
Yeah we don't fix Vanilla issues https://bugs.mojang.com/browse/MC-202202. I will close this, but we'd accept prs with workarounds, if those are possible without breaking other behavior.
