### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHAT_MESSAGE (0x0F)

### ISSUE THREAD

**Issue by voodootje0** [ViaVersion/ViaVersion#2232]
**Describe the bug, provide any errors**
https://haste.jartexnetwork.com/gugezobijo.bash

**How can we reproduce it?**
1. Use a plugin, or tell raw, that would use show_item in main chat.
2. Make sure to use an item name with \\\\\\\\\ inside it.
3. All clients above 1.12.2 will crash. (I tested it with my main on 1.8, and alt on 1.16.4, and it got kicked)

**Expected behaviour**
See above

**Screenshots**

**ViaVersion Dump**
https://dump.viaversion.com/b894fa24260c27b202a7a2477a1b084f90c4a770809118a14a7e05c9b0e3cadf
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by terrarier2111** [comment]
Your paste isn't working anymore could you please provide a new one?

**Comment by voodootje0** [comment]
@terrarier2111 Thanks for letting me know. 

Here is a new log: https://haste.jartexnetwork.com/itoraragihipoqim.yaml

**Comment by FormallyMyles** [comment]
This happens because \ is an escape character, e.g. "Hello \"World\"", but you can also escape an escape character e.g, "Hello \\World" -> Hello \World. An odd number of slashes means it will escape a letter hence in your example it's bad NBT and kicks you (because we can't recover from it).

You'd need to add an extra slash to the item data to correct this. If you have an idea of how we should correct this, we can look further but the slash character works like this for most versions.
