### ISSUE TITLE
Bad packet id 1000

### ISSUE THREAD

**Issue by LoXR** [ViaVersion/ViaVersion#2263]
**Describe the bug, provide any errors**
Paste: https://paste.gg/p/anonymous/db6eace9474147f2a1536b370ddbee47
It occurs on my 1.16 Creative server when someone joins on 1.8. And its a possibility of whats causing it to crash for some odd reason.

**How can we reproduce it?**
Unsure if they have vanilla or forge 1.8, as I dont get the console spam upon joining with 1.8

**Expected behaviour**
Hopefully a way to suppress the messages.

**Screenshots**
none

**ViaVersion Dump**
https://dump.viaversion.com/2248cba2867941ff952b2de0300a31fa15f2e046028201140b9fe8056e5cd636

**Additional server info**
Server is behind Proxy, and using git-Paper-343 at the time of this report.

**Checklist**
- [ X] I have included a Viaversion dump
- [ X] If applicable, I have included a paste (not a screenshot) of the error
- [X ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
I don't believe there's a nice fix to this as I believe in vanilla the server would most likely also error. If it happens consistently best case is to use a ConsoleSpam fixing plugin. Mainly because these kind of errors are useful for when we do make mistakes and hiding them would potentially limit us on fixing packet id errors.

If there's any other suggestions, they're welcome but this is cause of a modded client.
