### ISSUE TITLE
Via.getAPI().getPlayerVersion(player) returns the wrong version before PlayerJoinEvent and in PlayerQuitEvent

### ISSUE THREAD

**Issue by lokha** [ViaVersion/ViaVersion#2273]
server version: paperspigot 1.12.2
viaversion version: 3.2.0

```java
	@EventHandler(priority = EventPriority.HIGHEST)
	public void on(PlayerLoginEvent event) {
		Player player = event.getPlayer();
		int version = Via.getAPI().getPlayerVersion(player);

		// version is wrong
	}

	@EventHandler(priority = EventPriority.HIGHEST)
	public void on(PlayerJoinEvent event) {
		Player player = event.getPlayer();
		int version = Via.getAPI().getPlayerVersion(player);

		// version is correct
	}
	
	@EventHandler(priority = EventPriority.HIGHEST)
	public void on(PlayerQuitEvent event) {
		Player player = event.getPlayer();
		int version = Via.getAPI().getPlayerVersion(player);
		
		// version is wrong
	}
```

Wrong version is the version of the server core, not the player. in my case 340

considering that viaversion is introduced into the connection process at the LOGIN stage, it is strange that it does not support the version at the PlayerLoginEvent stage

in the case of PlayerQuitEvent, everything is more complicated, but this is also part of the bukkit api and I would also like to be able to get a version at this event

even if you can't do what I wrote about. make at least an exception instead of the false version. due to this behavior, I ran into an important bug in my code, where I used viaversion as a dependency

sorry my english translator. thanks in advance

**Comment by KennyTV** [comment]
In 3.3.0, the method will return -1 if the player no longer has an open connection (which is also the case in the quit event, because it has already been closed at that point), see https://github.com/ViaVersion/ViaVersion/commit/4cc8a3f092a46daf90d483c088cca822cb9c37d0. In the login event, we don't have a connection object set up, because the required info is only finalized in the login success, which only happens right after the event.
