### ISSUE TITLE
Crash Bug V2.0

### ISSUE THREAD

**Issue by Tree182** [ViaVersion/ViaVersion#2691]
### `/viaversion dump` Output

https://dump.viaversion.com/bbad5a638464cb2f95b978cfd74e956b3816f7bc610ad1cfc086175b5ca3b44c

### Console Error

https://paste.gg/p/anonymous/86f87dcce1ce45b1ada6b1f4b0f65551

### Bug Description

Link here to the previous report that you wrongly diagnosed:
https://github.com/ViaVersion/ViaVersion/issues/2690

You guys closed my previous report by wrongly diagnosing it and then claiming it wasn't your responsibility.

Well ive had to fix the issue myself and confirm that it is NOT a book crash as you wrongly diagnosed but an issue with chat packets. You advised me to get an anti-crash plugin, which I have and the crash plugin specifically defends against this but your plugin makes that impossible by bypassing the patch with your custom decoder.

To be clear, this is a Viabackwards issue that you could fix easily. When removing viabackwards and using protocol support, the issue goes away.

The issue is that viabackwards causes the problem by bypassing the regular fixes for this crash packet and it is your plugin that makes servers vaunrable!

For added info, the hacked client that causes it is the 1.12 version of 'Jessica'.

I hope that you fix this before it becomes a more widespread issue and causes problems for every server that uses your plugin.

### Steps to Reproduce

The hacked client that causes it is the 1.12 version of 'Jessica'.

### Expected Behavior

I expect the server not to crash due to your plugin 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 32 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 13 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-13%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 12 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Seanoo1** [comment]
Your protocollib is extremely outdated

**Comment by kennytv** [comment]
Please refrain from opening more issues on this, we can't help you if you don't want any help. To reiterate:
- The logs you sent do not indicate a crash
- The logs you sent do not indicate a chat packet being an issue
- If you don't want legacy issues, don't use/allow legacy versions (and if we were to do an attempt at preventing all possible 1.8-1.12 exploits, that would have  to do _**a lot**_)

The fact that it is possible to do almost everything you can do on a 1.8/1.12 server is very well known and may or may not be worked around in the future, but legacy issues are very low on our priority list (_**and this cannot be fixed without blindly/arbitrarily eliminating player sent data based on size in a variety of places**_).

In any case, the actual problem is not well represented and explained by the issues you are creating, so there is no point in keeping this open.

**Comment by RaphiMC** [comment]
This is literally the same paste link. You can clearly see, that the error happended in ViaRewind and has nothing to do with chat packets. Still not Via who is responsible for fixing this.
