### ISSUE TITLE
Loading terrain when joining a Velocity Server with 1.20.4 on 1.20.1 Paper subserver

### ISSUE THREAD

**Issue by chrischivlog** [ViaVersion/ViaVersion#3630]
### `/viaversion dump` Output

https://dump.viaversion.com/4b64d2d5f67a883744c627180de5e15037fbe14c6406fb3ade776616994147e1

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

We use Viaversion on our Velocity Proxy Server. When a player in versions 1.20.0, 1.20.1 and 1.20.2 enters the server, the loading animation is displayed briefly as usual. However, if a player with 1.20.3 or 1.20.4 enters the server, the loading screen freezes for about 30 seconds. We have already tried with newer or older Velocity versions, but always got the same result. 

If we install Viaversion on our subserver, the loading time is as usual even with 1.20.4. We use 1.20.1-R0.1-SNAPSHOT as subserver. 

Here we have also tried the image paper-1.20.1-196 with Velocity velocity-3.3.0-SNAPSHOT-316, also without success.

However, if we move Viaversion directly to our subserver, it works as expected.

### Steps to Reproduce

1. Login with a 1.20.4 client
2. Resourcepack is downloading
3. Screen shows up for about 30 seconds "Loading terrain"

### Expected Behavior

Normally you would expect a short loading time similar to version 1.20.1 or 1.20.2.

### Additional Server Info

We use Velocity as our Proxy Server. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--00ef92bc--b312%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--00ef92bc--b312%29-3498db?style=flat-square) </br>![Proxy is 4 builds behind](https://img.shields.io/badge/Your%20proxy%20is%204%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): 15 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by chrischivlog** [comment]
https://dump.viaversion.com/4b64d2d5f67a883744c627180de5e15037fbe14c6406fb3ade776616994147e1

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--408b420a--b316%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--408b420a--b316%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by BingYanchi** [comment]
I encountered the same situation. To add other errors:

I tried to use 1.20.4 to enter the 1.20.1/1.20.2 server, and there was not only a 30s wait for loading.

The following situations are rare:
After entering the server, some players cannot be seen (and cannot be seen in the tab player list)
The world won't load (it will refresh after teleporting with /tp)

**Comment by Aeltumn** [comment]
I've written a possible fix for this, it's a hacky fix so not good enough to make into a PR, but it can help to give more context on the problem:
https://github.com/Aeltumn/ViaVersion/commit/478a403c1b94cebbbc1af7e00ee0d442dd6e5671

Namely, from what I've seen the issue here is that ViaVersion bundles the chunk load event with the join/respawn packets. I think this breaks if the client is instead entering the configuration phase, which is what velocity does as of recent changes. I can't entirely confirm if that's the case, but I can confirm that bundling the load start with the world border initialization packet instead would fix the issue. The world border packet is always sent right before load start by a 1.20.4 client, so it works, but relying on the default server's implementation to link packets doesn't seem super safe.

I can confirm it does fix the issue though. Don't understand ViaVersion's code enough to make a cleaner/better patch though.
